#!/bin/sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "src\|cpt-toolkit" | grep ".\(vue\|js\)$" | grep -v "vendors")
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi
PASS=true
echo "Validating Javascript:"
# Check for eslint
which ./node_modules/.bin/eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m"
  exit 1
fi
./node_modules/.bin/eslint $STAGED_FILES
if [[ "$?" == 0 ]]; then
  echo "\t\033[32mESLint Passed: $FILE\033[0m"
else
  echo "\t\033[41mESLint Failed: $FILE\033[0m"
  PASS=false
fi
echo "\nJavascript validation completed!\n"
if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi
exit $?
